export const formRegex = {
    email: /^\w+@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$/,
    zip: /(^\d{5}$)|(^\d{5}-\d{4}$)/,
    alpha: /[A-Za-z]/g
};

export const states = [
    { value: "ak", text: "AK" },
    { value: "al", text: "AL" },
    { value: "ar", text: "AR" },
    { value: "az", text: "AZ" },
    { value: "ca", text: "CA" },
    { value: "co", text: "CO" },
    { value: "ct", text: "CT" },
    { value: "dc", text: "DC" },
    { value: "de", text: "DE" },
    { value: "fl", text: "FL" },
    { value: "ga", text: "GA" },
    { value: "hi", text: "HI" },
    { value: "ia", text: "IA" },
    { value: "id", text: "ID" },
    { value: "il", text: "IL" },
    { value: "in", text: "IN" },
    { value: "ks", text: "KS" },
    { value: "ky", text: "KY" },
    { value: "la", text: "LA" },
    { value: "ma", text: "MA" },
    { value: "md", text: "MD" },
    { value: "me", text: "ME" },
    { value: "mi", text: "MI" },
    { value: "mn", text: "MN" },
    { value: "mo", text: "MO" },
    { value: "ms", text: "MS" },
    { value: "mt", text: "MT" },
    { value: "nc", text: "NC" },
    { value: "nd", text: "ND" },
    { value: "ne", text: "NE" },
    { value: "nh", text: "NH" },
    { value: "nj", text: "NJ" },
    { value: "nm", text: "NM" },
    { value: "nv", text: "NV" },
    { value: "ny", text: "NY" },
    { value: "oh", text: "OH" },
    { value: "ok", text: "OK" },
    { value: "or", text: "OR" },
    { value: "pa", text: "PA" },
    { value: "ri", text: "RI" },
    { value: "sc", text: "SC" },
    { value: "sd", text: "SD" },
    { value: "tn", text: "TN" },
    { value: "tx", text: "TX" },
    { value: "ut", text: "UT" },
    { value: "va", text: "VA" },
    { value: "vt", text: "VT" },
    { value: "wa", text: "WA" },
    { value: "wi", text: "WI" },
    { value: "wv", text: "WV" },
    { value: "wy", text: "WY" }
];
